### ISSUE TITLE
facilities = manager.list_facilities() gives KeyError

### ISSUE THREAD

**Issue by chriswayg** [packethost/packet-python#1]
The first part, to show that my environment is working:
```
>>> import packet 
>>> manager = packet.Manager(auth_token="TOKEN")

>>> operating_systems = manager.list_operating_systems()
/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

>>> for operating_system in operating_systems:
...     print(operating_system)
...
centos_7 CentOS 7 centos 7
centos_6 CentOS 6 centos 6
coreos_beta CoreOS (beta) coreos beta
coreos_alpha CoreOS (alpha) coreos alpha
debian_7 Debian 7 debian 7
ubuntu_14_04 Ubuntu 14.04 LTS ubuntu 14.04
>>>
```
I always got a KeyError with:
```
>>> facilities = manager.list_facilities()

/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "packet/Manager.py", line 22, in list_facilities
    facility = Facility(jsoned)
  File "packet/Facility.py", line 10, in __init__
    self.href = data['href']
KeyError: 'href'
```

This only worked after removing the line    ```self.href = data['href']``` in packet/Facility.py

Also in the Readme, it should be device.state not *device.status*, for example:
```
for device in devices:
...     print(device.hostname)
...     print(device.id)
...     print(device.state)
```
Environment Mac OS X Yosemite:
```
python --version
Python 2.7.6
```

**Comment by mustela** [comment]
Hi @chriswayg, I just committed an small change, would you mind to update your lib and try again? 

Thanks!

**Comment by mustela** [comment]
@chriswayg will just close this one. Please feel free to reopen if the issue persists.
